[target.x86_64-pc-windows-gnu]
pre-build = ["apt-get update && apt-get install --assume-yes --no-install-recommends libclang-10-dev clang-10"]

[target.x86_64-unknown-linux-gnu]
dockerfile = "./x86_64-unknown-linux-gnu.Dockerfile"

[target.wasm32-unknown-emscripten]
pre-build = ["apt-get update && apt-get install --assume-yes --no-install-recommends libclang-10-dev clang-10 emscripten"]
