name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.target }} --release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: |
            ${{ matrix.target == 'x86_64-pc-windows-gnu' && 'target/x86_64-pc-windows-gnu/release/dungeon_crawler.exe' }}
            ${{ matrix.target == 'x86_64-unknown-linux-gnu' && 'target/x86_64-unknown-linux-gnu/release/dungeon_crawler' }}
          asset_name: dungeon_crawler
          tag: ${{ github.ref }}
